from __future__ import annotations

import datetime
import sqlite3
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from flask import Flask, redirect, render_template, request, url_for

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "blogger.db"

app = Flask(__name__)


@dataclass
class BlogPost:
    id: int
    title: str
    keywords: str
    content: str
    banner: str
    status: str
    created_at: str
    updated_at: str
    approved_by: str | None
    social_posted: int


def get_connection() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    with get_connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS posts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                keywords TEXT NOT NULL,
                content TEXT NOT NULL,
                banner TEXT NOT NULL,
                status TEXT NOT NULL,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL,
                approved_by TEXT,
                social_posted INTEGER NOT NULL DEFAULT 0
            );
            """
        )
        conn.commit()


def fetch_posts(status: str | None = None) -> list[BlogPost]:
    query = "SELECT * FROM posts"
    params: Iterable[str] = []
    if status:
        query += " WHERE status = ?"
        params = [status]
    query += " ORDER BY created_at DESC"
    with get_connection() as conn:
        rows = conn.execute(query, params).fetchall()
    return [BlogPost(**row) for row in rows]


def fetch_post(post_id: int) -> BlogPost | None:
    with get_connection() as conn:
        row = conn.execute("SELECT * FROM posts WHERE id = ?", (post_id,)).fetchone()
    return BlogPost(**row) if row else None


def generate_blog_content(topic: str, keywords: str) -> tuple[str, str, str]:
    title = f"{topic.title()}: A Fresh Look at {keywords.title()}"
    banner = f"{topic.title()} • {keywords.title()}"
    today = datetime.date.today().strftime("%B %d, %Y")
    content = (
        f"## {title}\n\n"
        f"**Date:** {today}\n\n"
        f"In this edition, we explore {topic.lower()} using the latest insights around {keywords}. "
        "We unpack trends, highlight practical takeaways, and suggest next steps for your team.\n\n"
        "### Key Highlights\n"
        f"- Why {keywords} matters right now\n"
        f"- How {topic} is evolving in 2024\n"
        "- Immediate actions you can take today\n\n"
        "### Practical Takeaways\n"
        "1. Validate the audience need with a quick survey.\n"
        "2. Build a short pilot to capture learnings.\n"
        "3. Share results internally and iterate.\n\n"
        "_This draft was generated by the AI assistant. Review and adjust before publishing._"
    )
    return title, banner, content


def create_post(topic: str, keywords: str, content: str, banner: str) -> None:
    now = datetime.datetime.now(tz=datetime.timezone.utc).isoformat()
    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO posts (title, keywords, content, banner, status, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (topic, keywords, content, banner, "pending", now, now),
        )
        conn.commit()


def update_post(post_id: int, content: str, banner: str, status: str, approved_by: str | None) -> None:
    now = datetime.datetime.now(tz=datetime.timezone.utc).isoformat()
    with get_connection() as conn:
        conn.execute(
            """
            UPDATE posts
            SET content = ?, banner = ?, status = ?, approved_by = ?, updated_at = ?
            WHERE id = ?
            """,
            (content, banner, status, approved_by, now, post_id),
        )
        conn.commit()


def mark_social_posted(post_id: int) -> None:
    now = datetime.datetime.now(tz=datetime.timezone.utc).isoformat()
    with get_connection() as conn:
        conn.execute(
            """
            UPDATE posts
            SET social_posted = 1, updated_at = ?
            WHERE id = ?
            """,
            (now, post_id),
        )
        conn.commit()


@app.route("/")
def index() -> str:
    posts = fetch_posts()
    return render_template("index.html", posts=posts)


@app.route("/create")
def create() -> str:
    return render_template("create.html")


@app.route("/generate", methods=["POST"])
def generate() -> str:
    topic = request.form.get("topic", "").strip()
    keywords = request.form.get("keywords", "").strip()
    manual_content = request.form.get("manual_content", "").strip()

    if manual_content:
        title = topic or "Manual Draft"
        banner = request.form.get("banner", "").strip() or title
        content = manual_content
    else:
        title, banner, content = generate_blog_content(topic or "Your Topic", keywords or "Key themes")

    create_post(title, keywords or "manual", content, banner)
    return redirect(url_for("index"))


@app.route("/admin")
def admin() -> str:
    posts = fetch_posts(status="pending")
    return render_template("admin.html", posts=posts)


@app.route("/admin/post/<int:post_id>")
def admin_post(post_id: int) -> str:
    post = fetch_post(post_id)
    if not post:
        return redirect(url_for("admin"))
    return render_template("admin_post.html", post=post)


@app.route("/admin/post/<int:post_id>/approve", methods=["POST"])
def approve_post(post_id: int) -> str:
    content = request.form.get("content", "")
    banner = request.form.get("banner", "")
    approved_by = request.form.get("approved_by", "Admin")
    update_post(post_id, content, banner, "approved", approved_by)
    return redirect(url_for("admin"))


@app.route("/admin/post/<int:post_id>/needs-edit", methods=["POST"])
def needs_edit(post_id: int) -> str:
    content = request.form.get("content", "")
    banner = request.form.get("banner", "")
    update_post(post_id, content, banner, "needs_edit", None)
    return redirect(url_for("admin"))


@app.route("/post/<int:post_id>")
def view_post(post_id: int) -> str:
    post = fetch_post(post_id)
    if not post:
        return redirect(url_for("index"))
    return render_template("post.html", post=post)


@app.route("/social/post/<int:post_id>", methods=["POST"])
def social_post(post_id: int) -> str:
    post = fetch_post(post_id)
    if post and post.status == "approved":
        mark_social_posted(post_id)
    return redirect(url_for("view_post", post_id=post_id))


if __name__ == "__main__":
    init_db()
    app.run(host="0.0.0.0", port=5000, debug=True)
